# Model config

NUM_INPUT_PLANES: 83

NUM_FILTERS: 64
KERNEL_SIZE: 3
STRIDE: 1
NUM_RES_BLOCKS: 10

NUM_FILTERS_POLICY: 2
KERNEL_SIZE_POLICY: 1

NUM_FILTERS_HEAD: 1
KERNEL_SIZE_HEAD: 1
NUM_HEAD_DENSE_LAYER_OUTPUT_1: 128
NUM_HEAD_DENSE_LAYER_OUTPUT_2: 1

# Optimizer config

MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001
LEARNING_RATE: 0.01

# Training config

NUM_PLAYOUTS_PER_GAME: 1600
NUM_GAMES_PER_ITERATION: 50
NUM_STEPS_PER_ITERATION: 1000
CPUCT: 1.0
BATCH_SIZE: 128
