NUM_INPUT_PLANES: 83

NUM_FILTERS: 256
KERNEL_SIZE: 3
STRIDE: 1
NUM_RES_BLOCKS: 19

NUM_FILTERS_POLICY: 2
KERNEL_SIZE_POLICY: 1

NUM_FILTERS_HEAD: 1
KERNEL_SIZE_HEAD: 1
NUM_HEAD_DENSE_LAYER_OUTPUT_1: 256
NUM_HEAD_DENSE_LAYER_OUTPUT_2: 1

MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001
LEARNING_RATE: 0.01
